### ISSUE TITLE
[BUG] clean meeting failed: 500 get all rooms error, login and clean previous rooms=1: twirp error unauthenticated: Error from intermediary with HTTP status code 401 \"Unauthorized\" get all rooms error, login and clean previous rooms=1: twirp error unauthenticated: Error from intermediary with HTTP status code 401 \"Unauthorized\"

### ISSUE THREAD

**Issue by bright87** [openimsdk/openmeeting-server#14]
### OpenIM Server Version

当前版本，找不到你们的版本号

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

# 1. 代码git地址
https://github.com/openimsdk/openmeeting-server.git

# 2. 安装步骤
https://github.com/openimsdk/openmeeting-server/blob/main/README.md
都是按照文档中的步骤部署的。
OpenMeeting Server Source Code Deployment
## （1）. Downloading the Source Code
git clone https://github.com/openimsdk/openmeeting-server.git && cd openmeeting-server
### install dependencies component
docker compose up -d

### Checking if Related Dependencies components are Running Properly
docker ps
## （3）. Set external IP
Modify the `url` in `config/live.yml` to `ws://external_IP:17880` or a domain name.
## （4）. Initialization
Before the first compilation, execute on Linux/Mac platforms:

bash bootstrap.sh
On Windows execute:

bootstrap.bat
## （5）. compile and run
mage && mage start

### docker容器
```
[root@localhost ~]# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED      STATUS      PORTS                                                                                                                                   NAMES
cfe4f9c6387a   livekit/livekit-server:latest   "/livekit-server --c…"   6 days ago   Up 6 days   0.0.0.0:17880->7880/tcp, :::17880->7880/tcp, 0.0.0.0:17881->7881/tcp, :::17881->7881/tcp, 0.0.0.0:17882->7882/udp, :::17882->7882/udp   livekit
2764886dcd0e   mongo:6.0.2                     "docker-entrypoint.s…"   6 days ago   Up 6 days   0.0.0.0:37017->27017/tcp, :::37017->27017/tcp                                                                                           mongo
797b68f5d363   quay.io/coreos/etcd:v3.5.13     "/usr/local/bin/etcd"    6 days ago   Up 6 days   0.0.0.0:12379->2379/tcp, :::12379->2379/tcp, 0.0.0.0:12380->2380/tcp, :::12380->2380/tcp                                                etcd
fedbcd1097e8   redis:7.0.0                     "docker-entrypoint.s…"   6 days ago   Up 6 days   0.0.0.0:16379->6379/tcp, :::16379->6379/tcp                                                                                             redis
```

### openmeeting服务
```
[root@localhost ~]# ps aux | grep openmeeting
root     23974  0.0  0.0 1255280 26308 ?       Sl   Aug12   0:04 /usr/local/openmeeting-server/_output/bin/platforms/linux/amd64/openmeeting-api -i 0 -c /usr/local/openmeeting-server/config/
root     23975  0.0  0.0 1260172 27992 ?       Sl   Aug12   0:23 /usr/local/openmeeting-server/_output/bin/platforms/linux/amd64/openmeeting-admin-api -i 0 -c /usr/local/openmeeting-server/config/
root     23976  0.0  0.0 1257096 32148 ?       Sl   Aug12   0:50 /usr/local/openmeeting-server/_output/bin/platforms/linux/amd64/openmeeting-rpc-user -i 0 -c /usr/local/openmeeting-server/config/
root     23981  0.0  0.0 1260816 32740 ?       Sl   Aug12   0:51 /usr/local/openmeeting-server/_output/bin/platforms/linux/amd64/openmeeting-rpc-meeting -i 0 -c /usr/local/openmeeting-server/config/
root     24281  0.0  0.0 108096   620 pts/0    S+   Aug12   0:00 tail -f /var/log/openmeeting-server/openim-service-log.2024-08-12
```

# 3. 注册用户
```
curl -X POST "http://192.168.23.248:10022/admin/user/register" \
-H "Content-Type: application/json" \
-H "operationID: 123456789" \
-d '{
  "userID": "1",
  "password": "123456",
  "account": "dongliangzhi",
  "nickname": "董亮之"
}'
```
![2024-08-13_103557](https://github.com/user-attachments/assets/d59e6775-81ff-466e-9652-2712fd475598)

# 4. 登录
响应信息：
```
{
	"errCode": 500,
	"errMsg": "clean meeting failed: 500 get all rooms error, login and clean previous rooms=1: twirp error unauthenticated: Error from intermediary with HTTP status code 401 \"Unauthorized\" get all rooms error, login and clean previous rooms=1: twirp error unauthenticated: Error from intermediary with HTTP status code 401 \"Unauthorized\"",
	"errDlt": "clean meeting failed: 500 get all rooms error, login and clean previous rooms=1: twirp error unauthenticated: Error from intermediary with HTTP status code 401 \"Unauthorized\" get all rooms error, login and clean previous rooms=1: twirp error unauthenticated: Error from intermediary with HTTP status code 401 \"Unauthorized\""
}
```
![2024-08-13_103816](https://github.com/user-attachments/assets/d0abb13e-7997-4263-a9c4-09cc88678804)

# 配置文件
## discovery.yml
```
enable: "etcd"
etcd:
  rootDirectory: openmeeting
  address: [ 192.168.23.248:12379 ]
  username: ''
  password: ''
```

## livekit.yml
```
url: [ "ws://192.168.23.248:17880" ]
apiKey: "APIftrpEkL9x2pa"
apiSecret: "23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3"
innerURL: "ws://192.168.23.248:17880"
```

## log.yml
```
# Log storage path, default is acceptable, change to a full path if modification is needed
#storageLocation: ../../../../logs/
storageLocation: C:/worklog/log/openmeeting-server/
# Log rotation period (in hours), default is acceptable
rotationTime: 24
# Number of log files to retain, default is acceptable
remainRotationCount: 2
# Log level settings: 3 for production environment; 6 for more verbose logging in debugging environments
remainLogLevel: 6
# Whether to output to standard output, default is acceptable
isStdout: false
# Whether to log in JSON format, default is acceptable
isJson: false
# output simplify log when KeyAndValues's value len is bigger than 50 in rpc method log
isSimplify: true
```

## mongodb.yml
```
# URI for database connection, leave empty if using address and credential settings directly
uri: ''
# List of MongoDB server addresses
address: [ 192.168.23.248:37017 ]
# Name of the database
database: openmeeting_v1
# Username for database authentication
username: "openmeeting"
# Password for database authentication
password: "openmeeting123"
# Maximum number of connections in the connection pool
maxPoolSize: 100
# Maximum number of retry attempts for a failed database connection
maxRetry: 10
```

## openmeeting-admin-api.yml
```
expire: 1
secret: "sdASD@#(231"
api:
  # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, default is recommended
  listenIP: 0.0.0.0
  # Listening ports; if multiple are configured, multiple instances will be launched, must be consistent with the number of prometheus.ports
  ports: [ 10022 ]

prometheus:
  # Whether to enable prometheus
  enable: true
  # Prometheus listening ports, must match the number of api.ports
  ports: [ 20114 ]
  # This address can be accessed via a browser
  grafanaURL: http://127.0.0.1:13002/
```

## openmeeting-api.yml
```
secret: "sdASD@#(231"
api:
  # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, default is recommended
  listenIP: 0.0.0.0
  # Listening ports; if multiple are configured, multiple instances will be launched, must be consistent with the number of prometheus.ports
  ports: [ 10002 ]

prometheus:
  # Whether to enable prometheus
  enable: true
  # Prometheus listening ports, must match the number of api.ports
  ports: [ 20113 ]
  # This address can be accessed via a browser
  grafanaURL: http://127.0.0.1:13000/
```

## openmeeting-rpc-meeting.yml
```
rpc:
  # API or other RPCs can access this RPC through this IP; if left blank, the internal network IP is obtained by default
  registerIP: ''
  # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, if blank, the internal network IP is automatically obtained by default
  listenIP: 0.0.0.0
  # Listening ports; if multiple are configured, multiple instances will be launched, and must be consistent with the number of prometheus.ports
  ports: [ 10112 ]



prometheus:
  # Whether to enable prometheus
  enable: true
  # Prometheus listening ports, must be consistent with the number of rpc.ports
  ports: [ 20101 ]
```

## openmeeting-rpc-user.yml
```
rpc:
  # API or other RPCs can access this RPC through this IP; if left blank, the internal network IP is obtained by default
  registerIP: ''
  # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, if blank, the internal network IP is automatically obtained by default
  listenIP: 0.0.0.0
  # Listening ports; if multiple are configured, multiple instances will be launched, and must be consistent with the number of prometheus.ports
  ports: [ 10110 ]

token:
  expire: 1
  secret: "sdASD@#(231"

prometheus:
  # Whether to enable prometheus
  enable: true
  # Prometheus listening ports, must be consistent with the number of rpc.ports
  ports: [ 20100 ]
```

## redis.yml
```
address: [ 192.168.23.248:16379 ]
username: ''
password: openmeeting_v1
enablePipeline: false
clusterMode: false
db: 0
maxRetry: 10
```

## share.yml
```
rpcRegisterName:
  user: user
  meeting: meeting
```

**Comment by bright87** [comment]
# mogoDB中的用户数据
![image](https://github.com/user-attachments/assets/4cfddc3b-c965-4415-96e6-aae034a80edc)

# livekit.yml
```
url: [ "ws://192.168.23.248:17880" ] 
apiKey: "APIftrpEkL9x2pa" 
apiSecret: "23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3"
innerURL: "ws://192.168.23.248:17880"
```
只修改了url、innerURL这两项中的ip，livekit.yml其他配置项没有修改。

**Comment by bright87** [comment]
# 修改livekit服务配置文件
修改了livekit服务的配置文件：
/xx/openmeeting-server/components/livekit/config/livekit.yml
```
port: 7880
log_level: debug
rtc:
  port_range_start: 50000
  port_range_end: 60000
  tcp_port: 7881
  use_external_ip: true

#redis:
#  address: 127.0.0.1:16379
#  db: 2
#  password: openmeeting_v1

keys:
  #APIGPW3gnFTzqHH: 23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3
  APIftrpEkL9x2pa: 23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3

room:
  empty_timeout: 72000
  departure_timeout: 86400
```
将keys键值对设置为'/xx/openmeeting-server/config/livekit.yml'文件中apiKey和apiSecret的值。
apiKey为键，apiSecret为值。
```
url: [ "ws://192.168.23.248:17880" ]
apiKey: "APIftrpEkL9x2pa"
apiSecret: "23ztfSqsfQ8hKkHzHTl3Z4bvaxro0snjk5jwbp5p6Q3"
innerURL: "ws://192.168.23.248:17880"
```

# 新问题
```
{
	"errCode": 500,
	"errMsg": "clean meeting failed: 500 get all rooms error, login and clean previous rooms=1: twirp error internal: failed to do request: Post \"http://192.168.23.248:17880/twirp/livekit.RoomService/ListRooms\": dial tcp 192.168.23.248:17880: connect: connection refused get all rooms error, login and clean previous rooms=1: twirp error internal: failed to do request: Post \"http://192.168.23.248:17880/twirp/livekit.RoomService/ListRooms\": dial tcp 192.168.23.248:17880: connect: connection refused",
	"errDlt": "clean meeting failed: 500 get all rooms error, login and clean previous rooms=1: twirp error internal: failed to do request: Post \"http://192.168.23.248:17880/twirp/livekit.RoomService/ListRooms\": dial tcp 192.168.23.248:17880: connect: connection refused get all rooms error, login and clean previous rooms=1: twirp error internal: failed to do request: Post \"http://192.168.23.248:17880/twirp/livekit.RoomService/ListRooms\": dial tcp 192.168.23.248:17880: connect: connection refused"
}
```

# docker logs
```
2024-08-13T08:34:47.772169428Z could not validate RTC config: could not resolve external IP: context deadline exceeded
2024-08-13T08:35:34.919247136Z could not validate RTC config: could not resolve external IP: context deadline exceeded
```
